// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChnK56XrsmnksnmjZlaTv9StWYpWPelB8',
    appId: '1:975503412206:android:4417bd147b651fe4211cff',
    messagingSenderId: '975503412206',
    projectId: 'fruits-b3400',
    storageBucket: 'fruits-b3400.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVeUfi8FLewhH6mLurECkV6NPrMu4ebFY',
    appId: '1:975503412206:ios:efcf64b11eef34c1211cff',
    messagingSenderId: '975503412206',
    projectId: 'fruits-b3400',
    storageBucket: 'fruits-b3400.appspot.com',
    iosClientId: '975503412206-phknp3b1b90nd25hvnd3eu90ef50h3sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ0wvtEpoUSY1bd6-hHEUrSGngr54CFiY',
    appId: '1:975503412206:web:27f89644f5e46895211cff',
    messagingSenderId: '975503412206',
    projectId: 'fruits-b3400',
    authDomain: 'fruits-b3400.firebaseapp.com',
    storageBucket: 'fruits-b3400.appspot.com',
  );
}
